
[programs.devnet]
anchor_escrow = "3q6Sc7N5Z4UQQWa1TEgncVvabF9dBc4ubCJjBxRC4Cqm"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/rashidali/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
